version: '3.9'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db

volumes:
  db-data:
#  db:
#    image: postgres:17
#    container_name: wallet-db
#    env_file:
#      - .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: wallet-app
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      APP_PORT: ${APP_PORT}
#    ports:
#      - "${APP_PORT:-8080}:8080"
#
#volumes:
#  db_data: