spring:
  application:
    name: wallet
  jpa:
    show-sql: true
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  #    datasource:
  #      driver-class-name: org.postgresql.Driver
  #      url: jdbc:postgresql://${HOST}/learning-db
  #      username: ${DB_USER}
  #      password: ${DB_PASSWORD}

  datasource:
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
#    default-schema: public
#    user: ${DB_USER}
#    password: ${DB_PASSWORD}
server:
  port: 8080
