spring:
  application:
    name: wallet
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:walletDb}}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}

#  datasource:
#    url: jdbc:h2:mem:testDB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
#    default-schema: public
#    user: ${DB_USER}
#    password: ${DB_PASSWORD}

server:
  port: "${APP_PORT:8080}"
#spring:
#  datasource:
#    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:walleldb}}"
#    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
#    password: "${SPRING_DATASOURCE_PASSWORD:password}"
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#server:
#  port: "${APP_PORT:8080}"